### PR TITLE
Simple kadane.cpp

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by rsgilbert** [comment]
Hahaha. My first pull request, thank you. I will take my time to review your code and find out how I am supposed to merge it

**Comment by ghost** [comment]
Please check it and let me know if there are any issues. :)

**Review by rsgilbert — APPROVED** [review]
This is very good code. There is only one loop so it runs in O(n). At first it was running in 3 loops which doesnt scale well. Well done. Bravo!

**Comment by rsgilbert** [comment]
I've finished merging. Maybe we can work on another algorithm

**Comment by ghost** [comment]
Sure!

**Pull request merged**
